In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2], [3, 4]]
data_tensor = torch.tensor(data)
print(data_tensor, type(data_tensor))

tensor([[ 1,  2],
        [ 3,  4]]) <class 'torch.Tensor'>


In [3]:
data = [[1, 2], [3, 4], [5, 6]]
np_data = np.array(data)
print(np_data, type(np_data))
np_data_tensor = torch.from_numpy(np_data)
print(np_data_tensor, type(np_data_tensor))

[[1 2]
 [3 4]
 [5 6]] <class 'numpy.ndarray'>
tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6]]) <class 'torch.Tensor'>


In [4]:
torch.zeros(5)

tensor([ 0.,  0.,  0.,  0.,  0.])

In [5]:
torch.ones(2, 2)

tensor([[ 1.,  1.],
        [ 1.,  1.]])

In [6]:
torch.rand(3, 3, 3)

tensor([[[ 0.7491,  0.5463,  0.2877],
         [ 0.6172,  0.2110,  0.7374],
         [ 0.4222,  0.1182,  0.2003]],

        [[ 0.6468,  0.2717,  0.9566],
         [ 0.9109,  0.1452,  0.8817],
         [ 0.3024,  0.1230,  0.6179]],

        [[ 0.6607,  0.5619,  0.2037],
         [ 0.4687,  0.0173,  0.9288],
         [ 0.4127,  0.8780,  0.2986]]])

In [7]:
zero_tensor = torch.zeros(3, 3)
ones_like_zeros = torch.ones_like(zero_tensor)

print(zero_tensor.shape, ones_like_zeros.shape)

torch.Size([3, 3]) torch.Size([3, 3])


In [8]:
zero_tensor[0]

tensor([ 0.,  0.,  0.])

In [9]:
ones_like_zeros[:, 0]

tensor([ 1.,  1.,  1.])

In [10]:
x = ones_like_zeros.detach()
print(x)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])


In [11]:
x[:, 0] * 5

tensor([ 5.,  5.,  5.])

In [12]:
rand1 = torch.rand(5)
rand2 = torch.rand(5)
torch.matmul(rand1, rand2)

tensor(0.3728)

In [13]:
rand1 = torch.rand(5, 5)
rand2 = torch.rand(5, 5)
torch.matmul(rand1, rand2)

tensor([[ 1.6282,  2.0883,  1.5352,  1.9011,  1.4990],
        [ 1.8587,  2.0280,  2.0465,  2.1977,  1.3790],
        [ 1.1365,  1.4840,  1.1334,  1.6872,  1.0300],
        [ 1.7870,  2.2009,  1.8685,  2.2602,  1.7647],
        [ 0.9673,  1.1083,  1.4351,  1.6278,  0.7290]])